/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */

package ti.giphy

import androidx.appcompat.app.AppCompatActivity
import com.giphy.sdk.core.models.Media
import com.giphy.sdk.ui.GPHContentType
import com.giphy.sdk.ui.GPHSettings
import com.giphy.sdk.ui.Giphy
import com.giphy.sdk.ui.views.GiphyDialogFragment
import org.appcelerator.kroll.KrollDict
import org.appcelerator.kroll.KrollFunction
import org.appcelerator.kroll.KrollModule
import org.appcelerator.kroll.annotations.Kroll
import org.appcelerator.titanium.TiApplication

@Kroll.module(name = "TitaniumGiphy", id = "ti.giphy")
class TitaniumGiphyModule: KrollModule() {

	// Methods

	@Kroll.method
	fun initialize(params: KrollDict) {
		Giphy.configure(TiApplication.getAppCurrentActivity(), params.getString("apiKey"))
	}

	@Kroll.method
	fun showGIFDialog(params: KrollDict) {
		val callback = params["callback"] as KrollFunction
		val activity = TiApplication.getAppCurrentActivity() as AppCompatActivity

		val gphSettings = GPHSettings(enableEdgeToEdge = true)

		val dialog = GiphyDialogFragment.newInstance(gphSettings)
		dialog.gifSelectionListener = object: GiphyDialogFragment.GifSelectionListener {
			override fun didSearchTerm(term: String) {

			}

			override fun onDismissed(selectedContentType: GPHContentType) {

			}

			override fun onGifSelected(
				media: Media,
				searchTerm: String?,
				selectedContentType: GPHContentType
			) {
				val event = KrollDict()
				event["url"] = media.images.downsized?.gifUrl
				event["title"] = media.title
				event["contentUrl"] = media.contentUrl

				callback.callAsync(krollObject, event)
				dialog.dismiss()
			}
		}

		dialog.show(activity.supportFragmentManager, "giphy_dialog")
	}
}
